#!/bin/sh
# icon - IPMI console wrapper

PROG=`basename $0`
DIR=`dirname $0`
USAGE_TEXT="
$PROG - IPMI Console Wrapper
$PROG host [-u username] [-p] [command]
-u username     use username for login
-p              prompt for password
command         default command = sol activate
"

ARGS="-I lanplus"
USER=${ADMIN:-"ADMIN"}
PASS=${PASS:-"ADMIN"}

usage() {
    echo $USAGE_TEXT
}

while getopts hpu:x c; do
    case $c in
        h)      usage;
                exit;
                ;;
        p)      PASSPROMPT=1
                ;;
        u)      USER=$OPTARG
                ;;
    esac
done
shift `expr $OPTIND - 1`

if [ -z "$1" ]; then
    usage;
    exit 1;
fi

if [ "$PASSPROMPT" = "1" ]; then
    echo -n "Password: "
    stty -echo
    read PASS
    stty echo
fi

HOST=$1
shift
if [ -z "$HOST" ]; then
    echo "Usage: $0 host [-u username] [-p] [command]"
    exit 1
fi
CMD=$@
if [ -z "$CMD" ]; then
    CMD="sol activate"
fi

exec ipmitool $ARGS -U $USER -P $PASS -H $HOST $CMD
